### ISSUE TITLE
replace "File IO" with internal in comments

### ISSUE THREAD

**Issue by ahashibon** [simphony/simphony-jyulb#16]
comments in the internal wrapper still refer to the File IO wrapper:

https://github.com/simphony/simphony-jyulb/blob/feature-internal-wrapper/jyulb/internal/isothermal/jyu_engine.py

 """File-IO wrapper for the JYU-LB Isothermal 3D flow modeling engine.

**Comment by kemattil** [comment]
The comments have been corrected in #15. Also the README file is updated.

**Comment by kemattil** [comment]
Resolved in #15.
