### ISSUE TITLE
Use unittest template for testing ProxyLattice

### ISSUE THREAD

**Issue by kemattil** [simphony/simphony-jyulb#17]
Use the ABCCheckLattice test template from simphony-common.

Problem related to issue 80 in simphony-common (lattice size, origin, and base vector should always be 3D): should the index parameters for LatticeNode, get_node, iter_nodes, get_coordinate also always be in 3D (SSB decision)?

**Comment by tuopuu** [comment]
Test templates are now used for JYU-LB wrapper, implemented in #28 
Also, indices are now in 3D always.
