### ISSUE TITLE
Provide more information in README file

### ISSUE THREAD

**Issue by itziakos** [simphony/simphony-jyulb#2]
Please check the example in https://github.com/simphony/simphony-lammps-md/blob/master/README.rst

**Comment by kemattil** [comment]
There is now a pull request with modified README. Is it appropriate? I also added the coverage: for some reason the coverage percentage in the readme is unknown while travis check reports 89% (any ideas)?

**Comment by itziakos** [comment]
There are some timing issues with coveralls is should be fine after a while. Thanks for fixing this issue.
