### ISSUE TITLE
Installation document is not clear

### ISSUE THREAD

**Issue by mehdisadeghi** [simphony/simphony-jyulb#21]
While trying to install simphony-jyulb in a fresh virtualenv I came across a few ambiguities that prevent a user to install the software correctly. I open this issue to address them.
# Installation instructions

It is much better to mention explicitly how to install requirements and the package step by step, i.e. creating a virtualenv, installing dependencies and the package. This could be done by adding `virtualenv jyulbenv` and `source jyulbenv/bin/activate` and then `pip install -r dev_requirements` to the readme. 
# Implicit dependency

As I see in the setup.py file, the script needs JYU-LB headers to be available in a sub-directory of installation directory, however this not mentioned in the document. I think this could be addressed by mentioning this dependency and adding steps to installing JYU-LB properly before pointing to `python setup.py install`. Without these steps the installation will not complete.
# External dependencies

I think user is supposed to run `install_external` but this is not mentioned in the readme.
## Further improvements

The `install_external` script requires the user to run it with super access rights, however this is not necessary and could be easily avoided. I think this script can first try to read a `--prefix` input parameter and if it is empty then try to install to the default location (`/usr/local/bin/`). User then can call the script like this:

```
$ ./install_external.sh --prefix=~/.local/bin
```

It would be helpful to mention also how to add this directory to the path:

```
$ echo 'PATH=$PATH:~/.local/bin' >> ~/.bashrc
```

or how to export the required parameter before calling setup.py:

```
$ export PATH=$PATH:~/.local/bin; python setup.py install
```

Here is how I changed the script to reflect above changes:

```
#!/bin/bash
# install JYU-LB
prefix=/usr/local/bin/
args=$(getopt -l "prefix:" -o "s:h" -- "$@")

eval set -- "$args"

while [ $# -ge 1 ]; do
        case "$1" in
                --)
                    # No more options left.
                    shift
                    break
                   ;;
                -p|--prefix)
                        prefix="$2"
                        shift
                        ;;
                -h)
                        echo "Usage: ./install_external.sh [--prefix=somewhere]"
                        exit 0
                        ;;
        esac

        shift
done
echo "Installing to $prefix"

git clone https://github.com/simphony/JYU-LB.git
cd JYU-LB
make -j 2
ln -s  $(pwd)/bin/jyu_lb_isothermal.exe "$prefix/jyu_lb_isothermal.exe"
```

**Comment by nathanfranklin** [comment]
@kemattil , have you had time to look at this issue?

**Comment by kemattil** [comment]
I have no expertise on these issues. I propose @mehdisadeghi implements the necessary changes.

**Comment by nathanfranklin** [comment]
> I have no expertise on these issues. I propose @mehdisadeghi implements the necessary changes.

@mehdisadeghi  and @ahashibon

**Comment by mehdisadeghi** [comment]
Done through PO #23
