### ISSUE TITLE
required version of jyu-lb should be specified in documenation

### ISSUE THREAD

**Issue by nathanfranklin** [simphony/simphony-jyulb#22]
simphony-jyulb version 0.1.2 fails when using jyu-lb version 0.1.0.  The required version of jyu-lb should be communicated.

**Comment by nathanfranklin** [comment]
This relates to #21

**Comment by nathanfranklin** [comment]
@kemattil   This is a blocking issue for simphony-jyulb to be integrated in the next version of the simphony-framework.

A new release of jyu-lb needs to be made and then it would be best to add this version information to the simhpony-jyulb's README file (i.e. "jyu-lb versino x.x.x is required").

**Comment by nathanfranklin** [comment]
@mehdisadeghi

**Comment by mehdisadeghi** [comment]
@nathanfranklin I made a new release (0.1.1) and updated the README on simphony-jyulb. After merging the PR#23 it would be possible to create a new release on simphony-jyulb.

**Comment by nathanfranklin** [comment]
closed by #23
