### ISSUE TITLE
Consistent naming of proxy lattice objects

### ISSUE THREAD

**Issue by tuopuu** [simphony/simphony-jyulb#30]
Naming of proxy lattice object should be changed into a more consistent format, that also works with upcoming multiphase LB wrappers. Naming should reflect the data transfer type (internal or fileio), object type (lattice) and engine type (multiphase or singlephase).

**Comment by kemattil** [comment]
Perhaps we should use simple names (even a single/common name like ProxyLattice) and rely on the module/package for making the distinction?

**Comment by tuopuu** [comment]
> common name like ProxyLattice

In that case, we may have to reorganize the folder structure so that ProxyLattice belonging to a specific wrapper is located in its subfolder, and subfolder naming is done in a way that is easy to understand. Something like:
single_phase/fileio
single_phase/internal
multi_phase/fileio
multi_phase/internal
OR
fileio/single_phase
fileio/multi_phase
internal/single_phase
internal/multi_phase

**Comment by kemattil** [comment]
Yes, it would probably be wise to define guidelines for the organization any way (at least regarding the fileio/internal option) ...

**Comment by tuopuu** [comment]
Fixed in #28
